version: '3.4'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
  api:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=my_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432